server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
zuul:
  ignoreSecurityHeaders: false
  sensitiveHeaders: "*" #不忽略任何头部信息，所有header都转发到下游的资源服务器。上下游session共享
  routes:
    cloud-web-device: /portal/device/**
    cloud-auth: /portal/auth/**
spring:
  application:
    name: cloud-zuul
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 500
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
jwt:
  tokenHead: Bearer
  header: Authorization
  expiration: 1800
  secret: mySecret
  route:
    authentication:
      path: auth/login
      refresh: auth/refresh
      register: \auth/register\


